# Generated by Django 3.2 on 2021-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210411_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='available',
            field=models.IntegerField(default=1),
        ),
    ]
