# Generated by Django 3.2 on 2021-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210411_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedtasks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
